import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import '../tool/record_catalog_version.dart';

/// Het vastleggen van een catalogusuitgave: de constante in de catalogus en de
/// regel in de licentietabel.
///
/// Dit was handwerk, en handwerk dat aantoonbaar misging — de Makefile droeg een
/// MASWE-datum die een dag ouder was dan de catalogus, dus wie het advies van de
/// Makefile opvolgde zette de bundel administratief terug in de tijd. Nu doet
/// `scripts/refresh_catalogs.sh` het, en hier staat waarom dat te vertrouwen is.
///
/// De scherpste rand zit in de licentietabel: daar staat "MITRE CWE 4.20" één
/// regel boven "WSTG v4.2". Een ongegrensde vervanging van `4.2` maakt daar
/// `5.00` van — een licentiedocument dat een versie noemt die niet bestaat, in
/// precies het document dat een auditor krijgt voorgelegd.
void main() {
  const licenceTable = '''
| Dataset | Where | Upstream | Licence / terms |
|---|---|---|---|
| CWE — full list (969 weaknesses: id, name, description) | `assets/cwe/cwe_full.json` | MITRE CWE 4.20 | MITRE Terms of Use |
| OWASP WSTG checklist index (97 tests: id, canonical title, category) | `lib/services/wstg_catalog.dart` | OWASP Web Security Testing Guide v4.2 | **CC-BY-SA-4.0** |
| OWASP MASWE weakness list (78 weaknesses: id, title) plus a bridge | `lib/services/maswe_catalog.dart`, generated by `tool/build_maswe_catalog.dart` | OWASP MASWE, snapshot **2026-08-04** (no releases or tags) | **CC-BY-SA-4.0** |
''';

  group('de constante in de catalogus', () {
    const source = '''
/// De WSTG-uitgave die deze bundel weerspiegelt.
const wstgVersion = '4.2';
const wstgStandardLabel = 'OWASP WSTG v\$wstgVersion';
''';

    test('leest en schrijft precies die ene constante', () {
      expect(readConst(source, 'wstgVersion'), '4.2');
      final out = setConst(source, 'wstgVersion', '5.0');
      expect(out, contains("const wstgVersion = '5.0';"));
      expect(
        out,
        contains("const wstgStandardLabel = 'OWASP WSTG v\$wstgVersion';"),
        reason: 'de regels eromheen blijven ongemoeid',
      );
    });

    test('meldt een constante die er niet staat, in plaats van te raden', () {
      expect(readConst(source, 'mastgVersion'), isNull);
    });
  });

  group('de rij in de licentietabel', () {
    test('werkt versie én aantal bij op de juiste rij', () {
      final out = updateLicenceRow(
        licenceTable,
        marker: 'lib/services/wstg_catalog.dart',
        previousVersion: '4.2',
        version: '5.0',
        count: 112,
      )!;
      expect(out, contains('(112 tests: id, canonical title, category)'));
      expect(out, contains('Web Security Testing Guide v5.0'));
    });

    test('laat CWE 4.20 met rust bij een WSTG-bump van 4.2', () {
      final out = updateLicenceRow(
        licenceTable,
        marker: 'lib/services/wstg_catalog.dart',
        previousVersion: '4.2',
        version: '5.0',
        count: 97,
      )!;
      expect(
        out,
        contains('MITRE CWE 4.20'),
        reason:
            'de vervanging blijft binnen de rij, en binnen die rij binnen het '
            'hele versienummer',
      );
      expect(out, isNot(contains('5.00')));
      expect(
        out,
        contains('(969 weaknesses: id, name, description)'),
        reason: 'het aantal van een andere dataset beweegt niet mee',
      );
    });

    test('een datum-momentopname gaat net zo goed', () {
      final out = updateLicenceRow(
        licenceTable,
        marker: 'lib/services/maswe_catalog.dart',
        previousVersion: '2026-08-04',
        version: '2026-09-01',
        count: 80,
      )!;
      expect(out, contains('snapshot **2026-09-01**'));
      expect(out, contains('(80 weaknesses: id, title)'));
    });

    test('geen rij → null, zodat de aanroeper het kan melden', () {
      expect(
        updateLicenceRow(
          licenceTable,
          marker: 'lib/services/gaat_niet_bestaan.dart',
          previousVersion: '1.0',
          version: '2.0',
          count: 1,
        ),
        isNull,
      );
    });
  });

  group('het register', () {
    test('elke catalogus wijst naar bestanden die er echt zijn', () {
      // Hernoemt iemand een gegenereerd deel, dan telt dit gereedschap stil nul
      // items en schrijft het een leugen in de licentietabel. Hier valt dat om.
      for (final entry in catalogs.entries) {
        expect(
          File(entry.value.constFile).existsSync(),
          isTrue,
          reason: '${entry.key}: ${entry.value.constFile}',
        );
        for (final data in entry.value.dataFiles) {
          expect(
            File(data).existsSync(),
            isTrue,
            reason: '${entry.key}: $data',
          );
          expect(
            File(data).readAsStringSync(),
            contains(entry.value.entryToken),
            reason:
                '${entry.key}: "${entry.value.entryToken}" komt niet meer voor '
                'in $data — de telling zou nul worden',
          );
        }
      }
    });

    test('en naar een rij die in de licentietabel bestaat', () {
      final doc = File('docs/LICENSE_COMPLIANCE.md').readAsStringSync();
      for (final entry in catalogs.entries) {
        expect(
          doc
              .split('\n')
              .any(
                (l) => l.startsWith('|') && l.contains(entry.value.docMarker),
              ),
          isTrue,
          reason:
              '${entry.key}: geen rij met ${entry.value.docMarker} in '
              'docs/LICENSE_COMPLIANCE.md',
        );
      }
    });
  });
}
