// GEGENEREERD door tool/build_mastg_catalog.dart — niet met de
// hand bijwerken. Zie dat bestand voor de bron en de regels.
//
// OWASP MASTG, © de OWASP Foundation, CC-BY-SA-4.0. Gebundeld is
// alleen de test-index (id, titel, MASVS-categorie, MASWE-koppeling);
// de inhoud van de tests staat op mas.owasp.org.
part of 'mastg_catalog.dart';

/// De iOS-tests uit de MASTG-index (88).
const List<MastgTest> _iosTests = [
  MastgTest(
    id: 'MASTG-TEST-0209',
    title: 'Insufficient Key Sizes',
    platform: 'ios',
    category: 'MASVS-CRYPTO',
    weakness: 'MASWE-0009',
  ),
  MastgTest(
    id: 'MASTG-TEST-0210',
    title: 'Broken Symmetric Encryption Algorithms',
    platform: 'ios',
    category: 'MASVS-CRYPTO',
    weakness: 'MASWE-0020',
  ),
  MastgTest(
    id: 'MASTG-TEST-0211',
    title: 'Broken Hashing Algorithms',
    platform: 'ios',
    category: 'MASVS-CRYPTO',
    weakness: 'MASWE-0021',
  ),
  MastgTest(
    id: 'MASTG-TEST-0213',
    title: 'Use of Hardcoded Cryptographic Keys in Code',
    platform: 'ios',
    category: 'MASVS-CRYPTO',
    weakness: 'MASWE-0014',
  ),
  MastgTest(
    id: 'MASTG-TEST-0214',
    title: 'Hardcoded Cryptographic Keys in Files',
    platform: 'ios',
    category: 'MASVS-CRYPTO',
    weakness: 'MASWE-0014',
  ),
  MastgTest(
    id: 'MASTG-TEST-0215',
    title: 'Sensitive Data Not Marked For Backup Exclusion',
    platform: 'ios',
    category: 'MASVS-STORAGE',
    weakness: 'MASWE-0004',
  ),
  MastgTest(
    id: 'MASTG-TEST-0219',
    title: 'Testing for Debugging Symbols',
    platform: 'ios',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0093',
  ),
  MastgTest(
    id: 'MASTG-TEST-0220',
    title: 'Usage of Outdated Code Signature Format',
    platform: 'ios',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0104',
  ),
  MastgTest(
    id: 'MASTG-TEST-0228',
    title: 'Position Independent Code (PIC) not Enabled',
    platform: 'ios',
    category: 'MASVS-CODE',
    weakness: 'MASWE-0116',
  ),
  MastgTest(
    id: 'MASTG-TEST-0229',
    title: 'Stack Canaries Not enabled',
    platform: 'ios',
    category: 'MASVS-CODE',
    weakness: 'MASWE-0116',
  ),
  MastgTest(
    id: 'MASTG-TEST-0230',
    title: 'Automatic Reference Counting (ARC) not enabled',
    platform: 'ios',
    category: 'MASVS-CODE',
    weakness: 'MASWE-0116',
  ),
  MastgTest(
    id: 'MASTG-TEST-0240',
    title: 'Jailbreak Detection in Code',
    platform: 'ios',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0097',
  ),
  MastgTest(
    id: 'MASTG-TEST-0241',
    title: 'Runtime Use of Jailbreak Detection Techniques',
    platform: 'ios',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0097',
  ),
  MastgTest(
    id: 'MASTG-TEST-0246',
    title: 'Runtime Use of Secure Screen Lock Detection APIs',
    platform: 'ios',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0008',
  ),
  MastgTest(
    id: 'MASTG-TEST-0248',
    title: 'References to APIs for Detecting Secure Screen Lock',
    platform: 'ios',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0008',
  ),
  MastgTest(
    id: 'MASTG-TEST-0261',
    title: 'Debuggable Entitlement Enabled in the entitlements.plist',
    platform: 'ios',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0067',
  ),
  MastgTest(
    id: 'MASTG-TEST-0266',
    title: 'References to APIs for Event-Bound Biometric Authentication',
    platform: 'ios',
    category: 'MASVS-AUTH',
    weakness: 'MASWE-0044',
  ),
  MastgTest(
    id: 'MASTG-TEST-0267',
    title: 'Runtime Use Of Event-Bound Biometric Authentication',
    platform: 'ios',
    category: 'MASVS-AUTH',
    weakness: 'MASWE-0044',
  ),
  MastgTest(
    id: 'MASTG-TEST-0268',
    title:
        'References to APIs Allowing Fallback to Non-Biometric Authentication',
    platform: 'ios',
    category: 'MASVS-AUTH',
    weakness: 'MASWE-0045',
  ),
  MastgTest(
    id: 'MASTG-TEST-0269',
    title:
        'Runtime Use Of APIs Allowing Fallback to Non-Biometric Authentication',
    platform: 'ios',
    category: 'MASVS-AUTH',
    weakness: 'MASWE-0045',
  ),
  MastgTest(
    id: 'MASTG-TEST-0270',
    title: 'References to APIs Detecting Biometric Enrollment Changes',
    platform: 'ios',
    category: 'MASVS-AUTH',
    weakness: 'MASWE-0046',
  ),
  MastgTest(
    id: 'MASTG-TEST-0271',
    title: 'Runtime Use Of APIs Detecting Biometric Enrollment Changes',
    platform: 'ios',
    category: 'MASVS-AUTH',
    weakness: 'MASWE-0046',
  ),
  MastgTest(
    id: 'MASTG-TEST-0273',
    title:
        'Identify Dependencies with Known Vulnerabilities by Scanning Dependency Managers Artifacts',
    platform: 'ios',
    category: 'MASVS-CODE',
    weakness: 'MASWE-0076',
  ),
  MastgTest(
    id: 'MASTG-TEST-0275',
    title: 'Dependencies with Known Vulnerabilities in the App\'s SBOM',
    platform: 'ios',
    category: 'MASVS-CODE',
    weakness: 'MASWE-0076',
  ),
  MastgTest(
    id: 'MASTG-TEST-0276',
    title: 'Use of the iOS General Pasteboard',
    platform: 'ios',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0053',
  ),
  MastgTest(
    id: 'MASTG-TEST-0277',
    title: 'Sensitive Data in the iOS General Pasteboard at Runtime',
    platform: 'ios',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0053',
  ),
  MastgTest(
    id: 'MASTG-TEST-0278',
    title: 'Pasteboard Contents Not Cleared After Use',
    platform: 'ios',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0053',
  ),
  MastgTest(
    id: 'MASTG-TEST-0279',
    title: 'Pasteboard Contents Not Expiring',
    platform: 'ios',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0053',
  ),
  MastgTest(
    id: 'MASTG-TEST-0280',
    title: 'Pasteboard Contents Not Restricted to Local Device',
    platform: 'ios',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0053',
  ),
  MastgTest(
    id: 'MASTG-TEST-0281',
    title: 'Undeclared Known Tracking Domains',
    platform: 'ios',
    category: 'MASVS-PRIVACY',
    weakness: 'MASWE-0108',
  ),
  MastgTest(
    id: 'MASTG-TEST-0290',
    title:
        'Runtime Verification of Sensitive Content Exposure in Screenshots During App Backgrounding',
    platform: 'ios',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0055',
  ),
  MastgTest(
    id: 'MASTG-TEST-0296',
    title: 'Sensitive Data Exposure in Logs',
    platform: 'ios',
    category: 'MASVS-STORAGE',
    weakness: 'MASWE-0001',
  ),
  MastgTest(
    id: 'MASTG-TEST-0297',
    title: 'Sensitive Data Exposure Through Logging APIs',
    platform: 'ios',
    category: 'MASVS-STORAGE',
    weakness: 'MASWE-0001',
  ),
  MastgTest(
    id: 'MASTG-TEST-0298',
    title: 'Runtime Monitoring of Files Eligible for Backup',
    platform: 'ios',
    category: 'MASVS-STORAGE',
    weakness: 'MASWE-0004',
  ),
  MastgTest(
    id: 'MASTG-TEST-0299',
    title: 'Data Protection Classes for Files in Private Storage',
    platform: 'ios',
    category: 'MASVS-STORAGE',
    weakness: 'MASWE-0006',
  ),
  MastgTest(
    id: 'MASTG-TEST-0300',
    title: 'References to APIs for Storing Unencrypted Data in Private Storage',
    platform: 'ios',
    category: 'MASVS-STORAGE',
    weakness: 'MASWE-0006',
  ),
  MastgTest(
    id: 'MASTG-TEST-0301',
    title:
        'Runtime Use of APIs for Storing Unencrypted Data in Private Storage',
    platform: 'ios',
    category: 'MASVS-STORAGE',
    weakness: 'MASWE-0006',
  ),
  MastgTest(
    id: 'MASTG-TEST-0302',
    title: 'Sensitive Data Unencrypted in Private Storage Files',
    platform: 'ios',
    category: 'MASVS-STORAGE',
    weakness: 'MASWE-0006',
  ),
  MastgTest(
    id: 'MASTG-TEST-0303',
    title: 'References to APIs for Storing Unencrypted Data in Shared Storage',
    platform: 'ios',
    category: 'MASVS-STORAGE',
    weakness: 'MASWE-0007',
  ),
  MastgTest(
    id: 'MASTG-TEST-0311',
    title: 'Insecure Random API Usage',
    platform: 'ios',
    category: 'MASVS-CRYPTO',
    weakness: 'MASWE-0027',
  ),
  MastgTest(
    id: 'MASTG-TEST-0313',
    title: 'References to APIs for Preventing Keyboard Caching of Text Fields',
    platform: 'ios',
    category: 'MASVS-STORAGE',
    weakness: 'MASWE-0053',
  ),
  MastgTest(
    id: 'MASTG-TEST-0314',
    title: 'Runtime Monitoring of Text Fields Eligible for Keyboard Caching',
    platform: 'ios',
    category: 'MASVS-STORAGE',
    weakness: 'MASWE-0053',
  ),
  MastgTest(
    id: 'MASTG-TEST-0317',
    title: 'Broken Symmetric Encryption Modes',
    platform: 'ios',
    category: 'MASVS-CRYPTO',
    weakness: 'MASWE-0020',
  ),
  MastgTest(
    id: 'MASTG-TEST-0321',
    title: 'Hardcoded HTTP URLs',
    platform: 'ios',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0050',
  ),
  MastgTest(
    id: 'MASTG-TEST-0322',
    title: 'App Transport Security Configurations Allowing Cleartext Traffic',
    platform: 'ios',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0050',
  ),
  MastgTest(
    id: 'MASTG-TEST-0323',
    title: 'Uses of Low-Level Networking APIs for Cleartext Traffic',
    platform: 'ios',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0050',
  ),
  MastgTest(
    id: 'MASTG-TEST-0331',
    title: 'Use of Deprecated WebView APIs',
    platform: 'ios',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0072',
  ),
  MastgTest(
    id: 'MASTG-TEST-0332',
    title: 'Attacker-Controlled URI in WebViews',
    platform: 'ios',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0071',
  ),
  MastgTest(
    id: 'MASTG-TEST-0333',
    title: 'Overly Broad File Read Access in WebViews',
    platform: 'ios',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0069',
  ),
  MastgTest(
    id: 'MASTG-TEST-0335',
    title: 'WebView File Origin Access Relaxed by Configuration',
    platform: 'ios',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0069',
  ),
  MastgTest(
    id: 'MASTG-TEST-0336',
    title: 'Runtime Setting of Relaxed WebView File Origin Policies',
    platform: 'ios',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0069',
  ),
  MastgTest(
    id: 'MASTG-TEST-0342',
    title: 'References to Weak ATS TLS Policy Exceptions in Info.plist',
    platform: 'ios',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0050',
  ),
  MastgTest(
    id: 'MASTG-TEST-0343',
    title: 'URLSession TLS Protocol Configuration',
    platform: 'ios',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0050',
  ),
  MastgTest(
    id: 'MASTG-TEST-0344',
    title: 'Network.framework TLS Protocol Configuration',
    platform: 'ios',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0050',
  ),
  MastgTest(
    id: 'MASTG-TEST-0345',
    title: 'Embedded or Third-party TLS Stack Configuration',
    platform: 'ios',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0050',
  ),
  MastgTest(
    id: 'MASTG-TEST-0346',
    title: 'References to APIs Hiding Sensitive Data in Text Input Fields',
    platform: 'ios',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0053',
  ),
  MastgTest(
    id: 'MASTG-TEST-0347',
    title: 'Runtime Use of APIs Hiding Sensitive Data in Text Input Fields',
    platform: 'ios',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0053',
  ),
  MastgTest(
    id: 'MASTG-TEST-0348',
    title: 'Insecure TLS Protocols in Network Traffic',
    platform: 'ios',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0050',
  ),
  MastgTest(
    id: 'MASTG-TEST-0349',
    title: 'Runtime Use of Insecure Random APIs',
    platform: 'ios',
    category: 'MASVS-CRYPTO',
    weakness: 'MASWE-0027',
  ),
  MastgTest(
    id: 'MASTG-TEST-0354',
    title: 'Runtime Use of Hook Detection Techniques',
    platform: 'ios',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0107',
  ),
  MastgTest(
    id: 'MASTG-TEST-0358',
    title: 'Implementation Details Exposure Through Logging APIs',
    platform: 'ios',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0094',
  ),
  MastgTest(
    id: 'MASTG-TEST-0359',
    title: 'Implementation Details Exposure in Logs',
    platform: 'ios',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0094',
  ),
  MastgTest(
    id: 'MASTG-TEST-0360',
    title: 'Purpose String Accuracy for Reachable Protected Resource Access',
    platform: 'ios',
    category: 'MASVS-PRIVACY',
    weakness: 'MASWE-0117',
  ),
  MastgTest(
    id: 'MASTG-TEST-0361',
    title:
        'Runtime Use of Protected Resource APIs Without Accurate Purpose Strings',
    platform: 'ios',
    category: 'MASVS-PRIVACY',
    weakness: 'MASWE-0117',
  ),
  MastgTest(
    id: 'MASTG-TEST-0362',
    title: 'Entitlements for Unjustified Capability Exposure',
    platform: 'ios',
    category: 'MASVS-PRIVACY',
    weakness: 'MASWE-0117',
  ),
  MastgTest(
    id: 'MASTG-TEST-0363',
    title:
        'Runtime Use of Entitlement-Backed APIs for Unjustified Capability Exposure',
    platform: 'ios',
    category: 'MASVS-PRIVACY',
    weakness: 'MASWE-0117',
  ),
  MastgTest(
    id: 'MASTG-TEST-0367',
    title: 'Runtime Use of Virtual Device Detection Techniques',
    platform: 'ios',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0099',
  ),
  MastgTest(
    id: 'MASTG-TEST-0370',
    title: 'Missing Input Validation in Custom URL Scheme Handlers',
    platform: 'ios',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0058',
  ),
  MastgTest(
    id: 'MASTG-TEST-0371',
    title: 'Missing Source Validation in Custom URL Scheme Handlers',
    platform: 'ios',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0058',
  ),
  MastgTest(
    id: 'MASTG-TEST-0376',
    title: 'References to Native Bridge APIs in WebViews',
    platform: 'ios',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0069',
  ),
  MastgTest(
    id: 'MASTG-TEST-0377',
    title:
        'References to `evaluateJavaScript` Used as Bridge Reply in `WKScriptMessageHandler`',
    platform: 'ios',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0069',
  ),
  MastgTest(
    id: 'MASTG-TEST-0378',
    title: 'References to Password Fields in WebView-Loaded HTML',
    platform: 'ios',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0069',
  ),
  MastgTest(
    id: 'MASTG-TEST-0379',
    title: 'References to `evaluateJavaScript` Without Content World Isolation',
    platform: 'ios',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0069',
  ),
  MastgTest(
    id: 'MASTG-TEST-0380',
    title:
        'References to `evaluateJavaScript` Writing Sensitive Data into WebView DOM',
    platform: 'ios',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0069',
  ),
  MastgTest(
    id: 'MASTG-TEST-0383',
    title: 'References to Enforced Updating APIs',
    platform: 'ios',
    category: 'MASVS-CODE',
    weakness: 'MASWE-0075',
  ),
  MastgTest(
    id: 'MASTG-TEST-0384',
    title: 'Runtime Use of Enforced Updating APIs',
    platform: 'ios',
    category: 'MASVS-CODE',
    weakness: 'MASWE-0075',
  ),
  MastgTest(
    id: 'MASTG-TEST-0385',
    title: 'Missing Certificate Pinning in ATS',
    platform: 'ios',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0047',
  ),
  MastgTest(
    id: 'MASTG-TEST-0386',
    title: 'References to Object Deserialization of Untrusted Data',
    platform: 'ios',
    category: 'MASVS-CODE',
    weakness: 'MASWE-0088',
  ),
  MastgTest(
    id: 'MASTG-TEST-0387',
    title: 'References to Storage Integrity Check APIs',
    platform: 'ios',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0105',
  ),
  MastgTest(
    id: 'MASTG-TEST-0388',
    title:
        'References to Sensitive Data Stored Unprotected in Shared App Group Containers',
    platform: 'ios',
    category: 'MASVS-STORAGE',
    weakness: 'MASWE-0006',
  ),
  MastgTest(
    id: 'MASTG-TEST-0389',
    title: 'References to the App-Wide Restriction of Custom Keyboards',
    platform: 'ios',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0061',
  ),
  MastgTest(
    id: 'MASTG-TEST-0390',
    title: 'Full Access Requested by a Custom Keyboard Extension',
    platform: 'ios',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0061',
  ),
  MastgTest(
    id: 'MASTG-TEST-0391',
    title: 'Insufficient Obfuscation of Security-Relevant Native Code',
    platform: 'ios',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0089',
  ),
  MastgTest(
    id: 'MASTG-TEST-0395',
    title: 'Missing Input Validation in Universal Link Handlers',
    platform: 'ios',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0058',
  ),
  MastgTest(
    id: 'MASTG-TEST-0396',
    title: 'References to URLSessionDelegate Bypassing Certificate Validation',
    platform: 'ios',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0052',
  ),
  MastgTest(
    id: 'MASTG-TEST-0397',
    title:
        'References to WKNavigationDelegate Bypassing Certificate Validation',
    platform: 'ios',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0052',
  ),
  MastgTest(
    id: 'MASTG-TEST-0401',
    title: 'References to Debugging Detection APIs',
    platform: 'ios',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0101',
  ),
  MastgTest(
    id: 'MASTG-TEST-0402',
    title: 'Runtime Use of Debugging Detection APIs',
    platform: 'ios',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0101',
  ),
];
