// GEGENEREERD door tool/build_mastg_catalog.dart — niet met de
// hand bijwerken. Zie dat bestand voor de bron en de regels.
//
// OWASP MASTG, © de OWASP Foundation, CC-BY-SA-4.0. Gebundeld is
// alleen de test-index (id, titel, MASVS-categorie, MASWE-koppeling);
// de inhoud van de tests staat op mas.owasp.org.
part of 'mastg_catalog.dart';

/// De Android-tests uit de MASTG-index (98).
const List<MastgTest> _androidTests = [
  MastgTest(
    id: 'MASTG-TEST-0200',
    title: 'Files Written to External Storage',
    platform: 'android',
    category: 'MASVS-STORAGE',
    weakness: 'MASWE-0007',
  ),
  MastgTest(
    id: 'MASTG-TEST-0201',
    title: 'Runtime Use of APIs to Access External Storage',
    platform: 'android',
    category: 'MASVS-STORAGE',
    weakness: 'MASWE-0007',
  ),
  MastgTest(
    id: 'MASTG-TEST-0202',
    title: 'References to APIs and Permissions for Accessing External Storage',
    platform: 'android',
    category: 'MASVS-STORAGE',
    weakness: 'MASWE-0007',
  ),
  MastgTest(
    id: 'MASTG-TEST-0203',
    title: 'Runtime Use of Logging APIs',
    platform: 'android',
    category: 'MASVS-STORAGE',
    weakness: 'MASWE-0001',
  ),
  MastgTest(
    id: 'MASTG-TEST-0204',
    title: 'Insecure Random API Usage',
    platform: 'android',
    category: 'MASVS-CRYPTO',
    weakness: 'MASWE-0027',
  ),
  MastgTest(
    id: 'MASTG-TEST-0205',
    title: 'Non-random Sources Usage',
    platform: 'android',
    category: 'MASVS-CRYPTO',
    weakness: 'MASWE-0027',
  ),
  MastgTest(
    id: 'MASTG-TEST-0206',
    title: 'Undeclared PII in Network Traffic Capture',
    platform: 'android',
    category: 'MASVS-PRIVACY',
    weakness: 'MASWE-0108',
  ),
  MastgTest(
    id: 'MASTG-TEST-0207',
    title: 'Runtime Storage of Unencrypted Data in the App Sandbox',
    platform: 'android',
    category: 'MASVS-STORAGE',
    weakness: 'MASWE-0006',
  ),
  MastgTest(
    id: 'MASTG-TEST-0208',
    title: 'Insufficient Key Sizes',
    platform: 'android',
    category: 'MASVS-CRYPTO',
    weakness: 'MASWE-0009',
  ),
  MastgTest(
    id: 'MASTG-TEST-0212',
    title: 'Use of Hardcoded Cryptographic Keys in Code',
    platform: 'android',
    category: 'MASVS-CRYPTO',
    weakness: 'MASWE-0014',
  ),
  MastgTest(
    id: 'MASTG-TEST-0216',
    title: 'Sensitive Data Not Excluded From Backup',
    platform: 'android',
    category: 'MASVS-STORAGE',
    weakness: 'MASWE-0004',
  ),
  MastgTest(
    id: 'MASTG-TEST-0217',
    title: 'Insecure TLS Protocols Explicitly Allowed in Code',
    platform: 'android',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0050',
  ),
  MastgTest(
    id: 'MASTG-TEST-0218',
    title: 'Insecure TLS Protocols in Network Traffic',
    platform: 'android',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0050',
  ),
  MastgTest(
    id: 'MASTG-TEST-0221',
    title: 'Broken Symmetric Encryption Algorithms',
    platform: 'android',
    category: 'MASVS-CRYPTO',
    weakness: 'MASWE-0020',
  ),
  MastgTest(
    id: 'MASTG-TEST-0222',
    title: 'Position Independent Code (PIC) Not Enabled',
    platform: 'android',
    category: 'MASVS-CODE',
    weakness: 'MASWE-0116',
  ),
  MastgTest(
    id: 'MASTG-TEST-0223',
    title: 'Stack Canaries Not Enabled',
    platform: 'android',
    category: 'MASVS-CODE',
    weakness: 'MASWE-0116',
  ),
  MastgTest(
    id: 'MASTG-TEST-0224',
    title: 'Usage of Insecure APK Signature Version',
    platform: 'android',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0104',
  ),
  MastgTest(
    id: 'MASTG-TEST-0225',
    title: 'Usage of Insecure APK Signature Key Size',
    platform: 'android',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0104',
  ),
  MastgTest(
    id: 'MASTG-TEST-0226',
    title: 'Debuggable Flag Enabled in the AndroidManifest',
    platform: 'android',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0067',
  ),
  MastgTest(
    id: 'MASTG-TEST-0227',
    title: 'Debugging Enabled for WebViews',
    platform: 'android',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0067',
  ),
  MastgTest(
    id: 'MASTG-TEST-0231',
    title: 'References to Logging APIs',
    platform: 'android',
    category: 'MASVS-STORAGE',
    weakness: 'MASWE-0001',
  ),
  MastgTest(
    id: 'MASTG-TEST-0232',
    title: 'Broken Symmetric Encryption Modes',
    platform: 'android',
    category: 'MASVS-CRYPTO',
    weakness: 'MASWE-0020',
  ),
  MastgTest(
    id: 'MASTG-TEST-0233',
    title: 'Hardcoded HTTP URLs',
    platform: 'android',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0050',
  ),
  MastgTest(
    id: 'MASTG-TEST-0234',
    title:
        'Missing Implementation of Server Hostname Verification with SSLSockets',
    platform: 'android',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0052',
  ),
  MastgTest(
    id: 'MASTG-TEST-0235',
    title: 'Android App Configurations Allowing Cleartext Traffic',
    platform: 'android',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0050',
  ),
  MastgTest(
    id: 'MASTG-TEST-0236',
    title: 'Cleartext Traffic Observed on the Network',
    platform: 'network',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0050',
  ),
  MastgTest(
    id: 'MASTG-TEST-0242',
    title: 'Missing Certificate Pinning in Network Security Configuration',
    platform: 'android',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0047',
  ),
  MastgTest(
    id: 'MASTG-TEST-0243',
    title: 'Expired Certificate Pins in the Network Security Configuration',
    platform: 'android',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0047',
  ),
  MastgTest(
    id: 'MASTG-TEST-0244',
    title: 'Missing Certificate Pinning in Network Traffic',
    platform: 'network',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0047',
  ),
  MastgTest(
    id: 'MASTG-TEST-0245',
    title: 'References to Platform Version APIs',
    platform: 'android',
    category: 'MASVS-CODE',
    weakness: 'MASWE-0077',
  ),
  MastgTest(
    id: 'MASTG-TEST-0247',
    title: 'References to APIs for Detecting Secure Screen Lock',
    platform: 'android',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0008',
  ),
  MastgTest(
    id: 'MASTG-TEST-0249',
    title: 'Runtime Use of Secure Screen Lock Detection APIs',
    platform: 'android',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0008',
  ),
  MastgTest(
    id: 'MASTG-TEST-0250',
    title: 'References to Content Provider Access in WebViews',
    platform: 'android',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0069',
  ),
  MastgTest(
    id: 'MASTG-TEST-0251',
    title: 'Runtime Use of Content Provider Access APIs in WebViews',
    platform: 'android',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0069',
  ),
  MastgTest(
    id: 'MASTG-TEST-0252',
    title: 'References to Local File Access in WebViews',
    platform: 'android',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0069',
  ),
  MastgTest(
    id: 'MASTG-TEST-0253',
    title: 'Runtime Use of Local File Access APIs in WebViews',
    platform: 'android',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0069',
  ),
  MastgTest(
    id: 'MASTG-TEST-0254',
    title: 'Dangerous App Permissions',
    platform: 'android',
    category: 'MASVS-PRIVACY',
    weakness: 'MASWE-0117',
  ),
  MastgTest(
    id: 'MASTG-TEST-0258',
    title: 'References to Keyboard Caching Attributes in UI Elements',
    platform: 'android',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0053',
  ),
  MastgTest(
    id: 'MASTG-TEST-0262',
    title: 'References to Backup Configurations Not Excluding Sensitive Data',
    platform: 'android',
    category: 'MASVS-STORAGE',
    weakness: 'MASWE-0004',
  ),
  MastgTest(
    id: 'MASTG-TEST-0263',
    title: 'Logging of StrictMode Violations',
    platform: 'android',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0094',
  ),
  MastgTest(
    id: 'MASTG-TEST-0264',
    title: 'Runtime Use of StrictMode APIs',
    platform: 'android',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0094',
  ),
  MastgTest(
    id: 'MASTG-TEST-0265',
    title: 'References to StrictMode APIs',
    platform: 'android',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0094',
  ),
  MastgTest(
    id: 'MASTG-TEST-0272',
    title:
        'Identify Dependencies with Known Vulnerabilities in the Android Project',
    platform: 'android',
    category: 'MASVS-CODE',
    weakness: 'MASWE-0076',
  ),
  MastgTest(
    id: 'MASTG-TEST-0274',
    title: 'Dependencies with Known Vulnerabilities in the App\'s SBOM',
    platform: 'android',
    category: 'MASVS-CODE',
    weakness: 'MASWE-0076',
  ),
  MastgTest(
    id: 'MASTG-TEST-0282',
    title: 'Unsafe Custom Trust Evaluation',
    platform: 'android',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0052',
  ),
  MastgTest(
    id: 'MASTG-TEST-0283',
    title: 'Incorrect Implementation of Server Hostname Verification',
    platform: 'android',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0052',
  ),
  MastgTest(
    id: 'MASTG-TEST-0284',
    title: 'Incorrect SSL Error Handling in WebViews',
    platform: 'android',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0052',
  ),
  MastgTest(
    id: 'MASTG-TEST-0285',
    title: 'Outdated Android Version Allowing Trust in User-Provided CAs',
    platform: 'android',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0052',
  ),
  MastgTest(
    id: 'MASTG-TEST-0286',
    title: 'Network Security Configuration Allowing Trust in User-Provided CAs',
    platform: 'android',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0052',
  ),
  MastgTest(
    id: 'MASTG-TEST-0287',
    title: 'Runtime Storage of Unencrypted Data via the SharedPreferences API',
    platform: 'android',
    category: 'MASVS-STORAGE',
    weakness: 'MASWE-0006',
  ),
  MastgTest(
    id: 'MASTG-TEST-0288',
    title: 'Debugging Symbols in Native Binaries',
    platform: 'android',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0093',
  ),
  MastgTest(
    id: 'MASTG-TEST-0289',
    title:
        'Runtime Verification of Sensitive Content Exposure in Screenshots During App Backgrounding',
    platform: 'android',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0055',
  ),
  MastgTest(
    id: 'MASTG-TEST-0291',
    title: 'References to Screen Capturing Prevention APIs',
    platform: 'android',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0055',
  ),
  MastgTest(
    id: 'MASTG-TEST-0295',
    title: 'GMS Security Provider Not Updated',
    platform: 'android',
    category: 'MASVS-NETWORK',
    weakness: 'MASWE-0052',
  ),
  MastgTest(
    id: 'MASTG-TEST-0307',
    title: 'References to Asymmetric Key Pairs Used For Multiple Purposes',
    platform: 'android',
    category: 'MASVS-CRYPTO',
    weakness: 'MASWE-0012',
  ),
  MastgTest(
    id: 'MASTG-TEST-0308',
    title: 'Runtime Use of Asymmetric Key Pairs Used For Multiple Purposes',
    platform: 'android',
    category: 'MASVS-CRYPTO',
    weakness: 'MASWE-0012',
  ),
  MastgTest(
    id: 'MASTG-TEST-0312',
    title: 'References to Explicit Security Provider in Cryptographic APIs',
    platform: 'android',
    category: 'MASVS-CRYPTO',
    weakness: 'MASWE-0020',
  ),
  MastgTest(
    id: 'MASTG-TEST-0315',
    title: 'Sensitive Data Exposed via Notifications',
    platform: 'android',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0054',
  ),
  MastgTest(
    id: 'MASTG-TEST-0316',
    title: 'App Exposing User Authentication Data in Text Input Fields',
    platform: 'android',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0053',
  ),
  MastgTest(
    id: 'MASTG-TEST-0318',
    title: 'References to SDK APIs Known to Handle Sensitive User Data',
    platform: 'android',
    category: 'MASVS-PRIVACY',
    weakness: 'MASWE-0112',
  ),
  MastgTest(
    id: 'MASTG-TEST-0319',
    title: 'Runtime Use of SDK APIs Known to Handle Sensitive User Data',
    platform: 'android',
    category: 'MASVS-PRIVACY',
    weakness: 'MASWE-0112',
  ),
  MastgTest(
    id: 'MASTG-TEST-0320',
    title: 'WebViews Not Cleaning Up Sensitive Data',
    platform: 'android',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0118',
  ),
  MastgTest(
    id: 'MASTG-TEST-0324',
    title: 'References to Root Detection Mechanisms',
    platform: 'android',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0097',
  ),
  MastgTest(
    id: 'MASTG-TEST-0325',
    title: 'Runtime Use of Root Detection Techniques',
    platform: 'android',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0097',
  ),
  MastgTest(
    id: 'MASTG-TEST-0326',
    title:
        'References to APIs Allowing Fallback to Non-Biometric Authentication',
    platform: 'android',
    category: 'MASVS-AUTH',
    weakness: 'MASWE-0045',
  ),
  MastgTest(
    id: 'MASTG-TEST-0327',
    title: 'References to APIs for Event-Bound Biometric Authentication',
    platform: 'android',
    category: 'MASVS-AUTH',
    weakness: 'MASWE-0044',
  ),
  MastgTest(
    id: 'MASTG-TEST-0328',
    title: 'References to APIs Detecting Biometric Enrollment Changes',
    platform: 'android',
    category: 'MASVS-AUTH',
    weakness: 'MASWE-0046',
  ),
  MastgTest(
    id: 'MASTG-TEST-0329',
    title:
        'References to APIs Enforcing Authentication without Explicit User Action',
    platform: 'android',
    category: 'MASVS-AUTH',
    weakness: 'MASWE-0044',
  ),
  MastgTest(
    id: 'MASTG-TEST-0330',
    title:
        'References to APIs for Keys used in Biometric Authentication with Extended Validity Duration',
    platform: 'android',
    category: 'MASVS-AUTH',
    weakness: 'MASWE-0044',
  ),
  MastgTest(
    id: 'MASTG-TEST-0334',
    title: 'Native Code Exposed Through WebViews',
    platform: 'android',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0069',
  ),
  MastgTest(
    id: 'MASTG-TEST-0337',
    title: 'References to Object Deserialization of Untrusted Data',
    platform: 'android',
    category: 'MASVS-CODE',
    weakness: 'MASWE-0088',
  ),
  MastgTest(
    id: 'MASTG-TEST-0338',
    title: 'References to Storage Integrity Check APIs',
    platform: 'android',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0105',
  ),
  MastgTest(
    id: 'MASTG-TEST-0339',
    title: 'SQL Injection in Content Providers',
    platform: 'android',
    category: 'MASVS-CODE',
    weakness: 'MASWE-0086',
  ),
  MastgTest(
    id: 'MASTG-TEST-0340',
    title: 'References to Overlay Attack Protections',
    platform: 'android',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0053',
  ),
  MastgTest(
    id: 'MASTG-TEST-0341',
    title: 'Runtime Use of Hook Detection Techniques',
    platform: 'android',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0107',
  ),
  MastgTest(
    id: 'MASTG-TEST-0350',
    title: 'Runtime Use of Broken Symmetric Encryption Modes',
    platform: 'android',
    category: 'MASVS-CRYPTO',
    weakness: 'MASWE-0020',
  ),
  MastgTest(
    id: 'MASTG-TEST-0351',
    title: 'Runtime Use of Emulator Detection Techniques',
    platform: 'android',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0099',
  ),
  MastgTest(
    id: 'MASTG-TEST-0352',
    title: 'References to Debugging Detection APIs',
    platform: 'android',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0101',
  ),
  MastgTest(
    id: 'MASTG-TEST-0353',
    title: 'Runtime Use of Debugging Detection APIs',
    platform: 'android',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0101',
  ),
  MastgTest(
    id: 'MASTG-TEST-0355',
    title:
        'References to Unauthorized Database Access through Content Providers',
    platform: 'android',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0064',
  ),
  MastgTest(
    id: 'MASTG-TEST-0356',
    title:
        'Runtime Verification of Unauthorized Database Access through Content Providers',
    platform: 'android',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0064',
  ),
  MastgTest(
    id: 'MASTG-TEST-0357',
    title: 'References to Oversharing of File-Based Content Providers',
    platform: 'android',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0064',
  ),
  MastgTest(
    id: 'MASTG-TEST-0364',
    title:
        'Exported And Unprotected Activities That Expose Sensitive Functionality',
    platform: 'android',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0119',
  ),
  MastgTest(
    id: 'MASTG-TEST-0365',
    title:
        'Exported And Unprotected Services That Expose Sensitive Functionality',
    platform: 'android',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0062',
  ),
  MastgTest(
    id: 'MASTG-TEST-0366',
    title:
        'Exported And Unprotected Broadcast Receivers That Expose Sensitive Functionality',
    platform: 'android',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0063',
  ),
  MastgTest(
    id: 'MASTG-TEST-0368',
    title: 'Insufficient Obfuscation of Security-Relevant Java/Kotlin Code',
    platform: 'android',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0089',
  ),
  MastgTest(
    id: 'MASTG-TEST-0369',
    title: 'Insufficient Obfuscation of Security-Relevant Native Code',
    platform: 'android',
    category: 'MASVS-RESILIENCE',
    weakness: 'MASWE-0089',
  ),
  MastgTest(
    id: 'MASTG-TEST-0372',
    title: 'Implicit Intents Used for Internal App Communication',
    platform: 'android',
    category: 'MASVS-CODE',
    weakness: 'MASWE-0066',
  ),
  MastgTest(
    id: 'MASTG-TEST-0374',
    title: 'References to Implicit Intents Carrying Sensitive Extras',
    platform: 'android',
    category: 'MASVS-CODE',
    weakness: 'MASWE-0066',
  ),
  MastgTest(
    id: 'MASTG-TEST-0375',
    title: 'Missing Validation of Data Returned from Implicit Intents',
    platform: 'android',
    category: 'MASVS-CODE',
    weakness: 'MASWE-0083',
  ),
  MastgTest(
    id: 'MASTG-TEST-0381',
    title: 'References to Insecure PendingIntent Creation',
    platform: 'android',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0066',
  ),
  MastgTest(
    id: 'MASTG-TEST-0382',
    title: 'Runtime Use of Enforced Updating APIs',
    platform: 'android',
    category: 'MASVS-CODE',
    weakness: 'MASWE-0075',
  ),
  MastgTest(
    id: 'MASTG-TEST-0392',
    title: 'References to Enforced Updating APIs',
    platform: 'android',
    category: 'MASVS-CODE',
    weakness: 'MASWE-0075',
  ),
  MastgTest(
    id: 'MASTG-TEST-0393',
    title: 'Use of Unverified App Links',
    platform: 'android',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0058',
  ),
  MastgTest(
    id: 'MASTG-TEST-0394',
    title: 'Missing Input Validation in Custom URL Scheme Handlers',
    platform: 'android',
    category: 'MASVS-PLATFORM',
    weakness: 'MASWE-0058',
  ),
  MastgTest(
    id: 'MASTG-TEST-0398',
    title: 'References to WebViewClient URL Loading Handlers',
    platform: 'android',
    category: 'MASVS-CODE',
    weakness: 'MASWE-0071',
  ),
  MastgTest(
    id: 'MASTG-TEST-0399',
    title: 'SafeBrowsing Disabled',
    platform: 'android',
    category: 'MASVS-CODE',
    weakness: 'MASWE-0071',
  ),
  MastgTest(
    id: 'MASTG-TEST-0400',
    title: 'Runtime Use of WebViewClient URL Loading Handlers',
    platform: 'android',
    category: 'MASVS-CODE',
    weakness: 'MASWE-0071',
  ),
];
