// GEGENEREERD door tool/build_maswe_catalog.dart — niet met de
// hand bijwerken. Zie dat bestand voor de bron en de regels.
//
// OWASP MASWE, © de OWASP Foundation, CC-BY-SA-4.0.
part of 'maswe_catalog.dart';

/// De MASWE-zwakheden (78), op id gesorteerd.
const List<MasweWeakness> _weaknesses = [
  MasweWeakness(
    id: 'MASWE-0001',
    title: 'Sensitive Data Stored Unencrypted in Private Storage',
    category: 'MASVS-STORAGE',
    platforms: ['android', 'ios'],
    cweIds: [200, 284, 312, 313, 732, 922],
    description: 'The app encrypts sensitive data stored in private storage.',
  ),
  MasweWeakness(
    id: 'MASWE-0002',
    title: 'Sensitive Data Stored Unencrypted Outside of Private Storage',
    category: 'MASVS-STORAGE',
    platforms: ['android', 'ios'],
    cweIds: [200, 284, 312, 313, 732, 921, 922],
    description:
        'The app encrypts sensitive data stored outside of private storage.',
  ),
  MasweWeakness(
    id: 'MASWE-0003',
    title: 'Cryptographic Keys Stored Outside of Platform Keystore',
    category: 'MASVS-STORAGE',
    platforms: ['android', 'ios'],
    cweIds: [312, 318, 321],
    description:
        'The app stores cryptographic keys inside the platform-provided secure keystore.',
  ),
  MasweWeakness(
    id: 'MASWE-0004',
    title: 'Sensitive Data Hardcoded in the App Package',
    category: 'MASVS-STORAGE',
    platforms: ['android', 'ios'],
    cweIds: [312, 321, 540, 798],
    description:
        'The app does not hardcode sensitive data in the application package.',
  ),
  MasweWeakness(
    id: 'MASWE-0005',
    title: 'Insertion of Sensitive Data into Logs',
    category: 'MASVS-STORAGE',
    platforms: ['android', 'ios'],
    cweIds: [209, 359, 497, 532],
    description: 'The app excludes sensitive data from application logs.',
  ),
  MasweWeakness(
    id: 'MASWE-0006',
    title: 'Sensitive Data Not Excluded From Backup',
    category: 'MASVS-STORAGE',
    platforms: ['android', 'ios'],
    cweIds: [212, 313],
    description: 'The app excludes sensitive data from backups.',
  ),
  MasweWeakness(
    id: 'MASWE-0007',
    title: 'Improper Encryption',
    category: 'MASVS-CRYPTO',
    platforms: ['android', 'ios'],
    cweIds: [208, 323, 325, 326, 327, 329, 780],
    description: 'The app properly encrypts sensitive data.',
  ),
  MasweWeakness(
    id: 'MASWE-0008',
    title: 'Improper Hashing',
    category: 'MASVS-CRYPTO',
    platforms: ['android', 'ios'],
    cweIds: [328],
    description: 'The app properly hashes sensitive data.',
  ),
  MasweWeakness(
    id: 'MASWE-0009',
    title: 'Improper Use of Message Authentication Code (MAC)',
    category: 'MASVS-CRYPTO',
    platforms: ['android', 'ios'],
    cweIds: [208, 323, 327, 354, 807],
    description: 'The app properly uses Message Authentication Codes (MACs).',
  ),
  MasweWeakness(
    id: 'MASWE-0010',
    title: 'Improper Generation of Cryptographic Signatures',
    category: 'MASVS-CRYPTO',
    platforms: ['android', 'ios'],
    cweIds: [323, 326, 327, 330],
    description: 'The app properly generates cryptographic signatures.',
  ),
  MasweWeakness(
    id: 'MASWE-0011',
    title: 'Improper Verification of Cryptographic Signature',
    category: 'MASVS-CRYPTO',
    platforms: ['android', 'ios'],
    cweIds: [295, 347],
    description: 'The app properly verifies cryptographic signatures.',
  ),
  MasweWeakness(
    id: 'MASWE-0012',
    title: 'Improper Random Number Generation',
    category: 'MASVS-CRYPTO',
    platforms: ['android', 'ios'],
    cweIds: [332, 337, 338],
    description: 'The app properly generates random numbers.',
  ),
  MasweWeakness(
    id: 'MASWE-0013',
    title: 'Improper Cryptographic Key Generation',
    category: 'MASVS-CRYPTO',
    platforms: ['android', 'ios'],
    cweIds: [331, 326, 337, 338, 522],
    description: 'The app securely generates cryptographic keys.',
  ),
  MasweWeakness(
    id: 'MASWE-0014',
    title: 'Improper Cryptographic Key Derivation',
    category: 'MASVS-CRYPTO',
    platforms: ['android', 'ios'],
    cweIds: [326, 327, 759, 760, 916],
    description:
        'The app derives cryptographic keys using approved key derivation functions.',
  ),
  MasweWeakness(
    id: 'MASWE-0015',
    title: 'Cryptographic Key Rotation Not Implemented',
    category: 'MASVS-CRYPTO',
    platforms: ['android', 'ios'],
    cweIds: [324],
    description: 'The app rotates cryptographic keys regularly.',
  ),
  MasweWeakness(
    id: 'MASWE-0016',
    title: 'Cryptographic Key Access Not Restricted',
    category: 'MASVS-CRYPTO',
    platforms: ['android', 'ios'],
    cweIds: [284, 306],
    description: 'The app restricts access to cryptographic keys.',
  ),
  MasweWeakness(
    id: 'MASWE-0017',
    title: 'Device Secure Lock Not Enforced',
    category: 'MASVS-CRYPTO',
    platforms: ['android', 'ios'],
    cweIds: [],
    description:
        'The app verifies that the device has a secure lock configured.',
  ),
  MasweWeakness(
    id: 'MASWE-0018',
    title: 'Lack of Authentication or Authorization on App Components',
    category: 'MASVS-AUTH',
    platforms: ['android', 'ios'],
    cweIds: [306, 749, 862, 863, 923, 926, 939, 940],
    description:
        'The app enforces authentication and authorization on its components.',
  ),
  MasweWeakness(
    id: 'MASWE-0019',
    title: 'Lack of Auto-fill Support for Credential Providers',
    category: 'MASVS-AUTH',
    platforms: ['android', 'ios'],
    cweIds: [287, 522],
    description: 'The app enables auto-fill support for credential providers.',
  ),
  MasweWeakness(
    id: 'MASWE-0020',
    title: 'Local Authentication Can Be Bypassed',
    category: 'MASVS-AUTH',
    platforms: ['android', 'ios'],
    cweIds: [285, 287, 312, 319, 326, 602, 603, 863, 922],
    description: 'The app implements local authentication securely.',
  ),
  MasweWeakness(
    id: 'MASWE-0021',
    title:
        'Fallback to Non-biometric Credentials Allowed for Sensitive Transactions',
    category: 'MASVS-AUTH',
    platforms: ['android', 'ios'],
    cweIds: [288, 287],
    description:
        'The app does not allow fallback to non-biometric credentials for sensitive transactions.',
  ),
  MasweWeakness(
    id: 'MASWE-0022',
    title: 'Crypto Keys Not Invalidated on New Biometric Enrollment',
    category: 'MASVS-AUTH',
    platforms: ['android', 'ios'],
    cweIds: [287, 522],
    description:
        'The app invalidates keys after any enrollment of new biometric data.',
  ),
  MasweWeakness(
    id: 'MASWE-0023',
    title: 'Step-Up Authentication Not Implemented for Sensitive Actions',
    category: 'MASVS-AUTH',
    platforms: ['android', 'ios'],
    cweIds: [306],
    description:
        'The app enforces step-up authentication before granting access to sensitive functionality.',
  ),
  MasweWeakness(
    id: 'MASWE-0024',
    title: 'Sensitive Data Accessible After Session Termination',
    category: 'MASVS-AUTH',
    platforms: ['android', 'ios'],
    cweIds: [285, 287, 613],
    description:
        'The app makes sensitive data inaccessible after session termination.',
  ),
  MasweWeakness(
    id: 'MASWE-0025',
    title: 'Lack of Non-Repudiation for Critical Actions',
    category: 'MASVS-AUTH',
    platforms: ['android', 'ios'],
    cweIds: [451, 778],
    description: 'The app ensures non-repudiation for critical actions.',
  ),
  MasweWeakness(
    id: 'MASWE-0026',
    title: 'Network Traffic Not Encrypted',
    category: 'MASVS-NETWORK',
    platforms: ['android', 'ios'],
    cweIds: [319],
    description: 'The app encrypts all network traffic.',
  ),
  MasweWeakness(
    id: 'MASWE-0027',
    title: 'Insecure Certificate Validation',
    category: 'MASVS-NETWORK',
    platforms: ['android', 'ios'],
    cweIds: [295, 297],
    description: 'The app validates certificates for all network traffic.',
  ),
  MasweWeakness(
    id: 'MASWE-0028',
    title: 'Insecure Identity Pinning',
    category: 'MASVS-NETWORK',
    platforms: ['android', 'ios'],
    cweIds: [295],
    description: 'The app correctly implements identity pinning.',
  ),
  MasweWeakness(
    id: 'MASWE-0029',
    title: 'Insecure Deep Links',
    category: 'MASVS-PLATFORM',
    platforms: ['android', 'ios'],
    cweIds: [939, 917],
    description: 'The app securely handles deep links.',
  ),
  MasweWeakness(
    id: 'MASWE-0030',
    title: 'Improper Use of the Clipboard',
    category: 'MASVS-PLATFORM',
    platforms: ['android', 'ios'],
    cweIds: [200, 668],
    description:
        'The app uses the clipboard securely and only with user consent.',
  ),
  MasweWeakness(
    id: 'MASWE-0031',
    title: 'Allowing Untrusted App Extensions',
    category: 'MASVS-PLATFORM',
    platforms: ['ios'],
    cweIds: [829],
    description:
        'The app only permits trusted app extensions to interact with it.',
  ),
  MasweWeakness(
    id: 'MASWE-0032',
    title: 'Insecure Intents',
    category: 'MASVS-PLATFORM',
    platforms: ['android'],
    cweIds: [927, 940],
    description: 'The app securely handles intents.',
  ),
  MasweWeakness(
    id: 'MASWE-0033',
    title: 'Sensitive Native Functionality Exposed in WebViews',
    category: 'MASVS-PLATFORM',
    platforms: ['android', 'ios'],
    cweIds: [749, 94],
    description:
        'The app does not expose sensitive native functionality to WebView content.',
  ),
  MasweWeakness(
    id: 'MASWE-0034',
    title: 'WebViews Allow Access to Local Resources with Untrusted Content',
    category: 'MASVS-PLATFORM',
    platforms: ['android', 'ios'],
    cweIds: [22, 79, 200, 669],
    description:
        'The app only allows trusted WebView content to access local resources.',
  ),
  MasweWeakness(
    id: 'MASWE-0035',
    title: 'WebViews Loading Untrusted Content',
    category: 'MASVS-PLATFORM',
    platforms: ['android', 'ios'],
    cweIds: [79, 601, 829],
    description: 'The app only allows trusted content in WebViews.',
  ),
  MasweWeakness(
    id: 'MASWE-0036',
    title: 'Unnecessary Exposure of Sensitive Data via the User Interface',
    category: 'MASVS-PLATFORM',
    platforms: ['android', 'ios'],
    cweIds: [200, 359],
    description:
        'The app does not unnecessarily expose sensitive data through its user interface.',
  ),
  MasweWeakness(
    id: 'MASWE-0037',
    title: 'Unnecessary Exposure of Sensitive Data via Notifications',
    category: 'MASVS-PLATFORM',
    platforms: ['android', 'ios'],
    cweIds: [200, 359],
    description:
        'The app does not unnecessarily expose sensitive data through system notifications.',
  ),
  MasweWeakness(
    id: 'MASWE-0038',
    title:
        'Insufficient Protection of Sensitive Data from Screenshots or Screen Recordings',
    category: 'MASVS-PLATFORM',
    platforms: ['android', 'ios'],
    cweIds: [200, 359],
    description:
        'The app removes or masks sensitive data from its views when moved to the background, when being recorded or when a screenshot is taken.',
  ),
  MasweWeakness(
    id: 'MASWE-0039',
    title: 'App Vulnerable to Overlay Attacks',
    category: 'MASVS-PLATFORM',
    platforms: ['android', 'ios'],
    cweIds: [1021],
    description:
        'The app protects its sensitive screens against overlay attacks.',
  ),
  MasweWeakness(
    id: 'MASWE-0040',
    title: 'Sensitive Data Leaked via Accessibility Services',
    category: 'MASVS-PLATFORM',
    platforms: ['android', 'ios'],
    cweIds: [200, 359],
    description:
        'The app prevents sensitive data from being exposed to, or captured by, accessibility services.',
  ),
  MasweWeakness(
    id: 'MASWE-0041',
    title: 'Running on a Recent Platform Version Not Ensured',
    category: 'MASVS-CODE',
    platforms: ['android', 'ios'],
    cweIds: [451, 693, 1104, 1357],
    description:
        'The app detects if it is running on an unsupported OS version and reacts appropriately.',
  ),
  MasweWeakness(
    id: 'MASWE-0042',
    title: 'Latest Platform Version Not Targeted',
    category: 'MASVS-CODE',
    platforms: ['android', 'ios'],
    cweIds: [693, 1357],
    description: 'The app targets the latest platform version.',
  ),
  MasweWeakness(
    id: 'MASWE-0043',
    title: 'Enforced Updating Not Implemented',
    category: 'MASVS-CODE',
    platforms: ['android', 'ios'],
    cweIds: [602, 693],
    description:
        'The app detects if it must be updated and reacts appropriately.',
  ),
  MasweWeakness(
    id: 'MASWE-0044',
    title: 'Dependencies with Known Vulnerabilities',
    category: 'MASVS-CODE',
    platforms: ['android', 'ios'],
    cweIds: [1395, 1357],
    description:
        'The app\'s third-party components are regularly checked for known vulnerabilities.',
  ),
  MasweWeakness(
    id: 'MASWE-0045',
    title: 'Compiler-Provided Security Features Not Used',
    category: 'MASVS-CODE',
    platforms: ['android', 'ios'],
    cweIds: [],
    description:
        'The app uses the compiler-provided security features of the platform.',
  ),
  MasweWeakness(
    id: 'MASWE-0046',
    title: 'Use of Deprecated APIs or Functionality',
    category: 'MASVS-CODE',
    platforms: ['android', 'ios'],
    cweIds: [327, 477, 522],
    description: 'The app does not use deprecated APIs or functionality.',
  ),
  MasweWeakness(
    id: 'MASWE-0047',
    title: 'Using Non-Standard APIs for Security-Critical Functionality',
    category: 'MASVS-CODE',
    platforms: ['android', 'ios'],
    cweIds: [287, 326, 327, 1240],
    description:
        'The app uses standard APIs for security-critical functionality.',
  ),
  MasweWeakness(
    id: 'MASWE-0048',
    title: 'Malicious Code Included in the App',
    category: 'MASVS-CODE',
    platforms: ['android', 'ios'],
    cweIds: [506, 507, 511],
    description: 'The app package does not contain malicious code.',
  ),
  MasweWeakness(
    id: 'MASWE-0049',
    title: 'Unsafe Dynamic Code Loading',
    category: 'MASVS-CODE',
    platforms: ['android', 'ios'],
    cweIds: [494],
    description: 'The app loads dynamic code safely from trusted sources.',
  ),
  MasweWeakness(
    id: 'MASWE-0050',
    title: 'Unsafe Handling of Untrusted Data',
    category: 'MASVS-CODE',
    platforms: ['android', 'ios'],
    cweIds: [20, 22, 73, 89, 116, 345, 348, 349, 502, 611, 924],
    description: 'The app securely handles untrusted data.',
  ),
  MasweWeakness(
    id: 'MASWE-0051',
    title: 'Root/Jailbreak Detection Not Implemented',
    category: 'MASVS-RESILIENCE',
    platforms: ['android', 'ios'],
    cweIds: [1326],
    description:
        'The app detects if it runs on a rooted/jailbroken device and reacts appropriately.',
  ),
  MasweWeakness(
    id: 'MASWE-0052',
    title: 'App Virtualization Environment Detection Not Implemented',
    category: 'MASVS-RESILIENCE',
    platforms: ['android', 'ios'],
    cweIds: [693],
    description:
        'The app detects when it is running inside an app-virtualization environment.',
  ),
  MasweWeakness(
    id: 'MASWE-0053',
    title: 'Emulated or Virtual Device Detection Not Implemented',
    category: 'MASVS-RESILIENCE',
    platforms: ['android', 'ios'],
    cweIds: [],
    description:
        'The app detects when it is running in an emulated or virtual device environment.',
  ),
  MasweWeakness(
    id: 'MASWE-0054',
    title: 'Device Attestation Not Implemented',
    category: 'MASVS-RESILIENCE',
    platforms: ['android', 'ios'],
    cweIds: [],
    description: 'The app implements device attestation.',
  ),
  MasweWeakness(
    id: 'MASWE-0055',
    title: 'Malware Detection Not Implemented',
    category: 'MASVS-RESILIENCE',
    platforms: ['android', 'ios'],
    cweIds: [693],
    description: 'The app detects attacks by malware.',
  ),
  MasweWeakness(
    id: 'MASWE-0056',
    title: 'App Attestation Not Implemented',
    category: 'MASVS-RESILIENCE',
    platforms: ['android', 'ios'],
    cweIds: [347],
    description: 'The app implements app attestation.',
  ),
  MasweWeakness(
    id: 'MASWE-0057',
    title: 'App Resources Integrity Not Verified',
    category: 'MASVS-RESILIENCE',
    platforms: ['android', 'ios'],
    cweIds: [471],
    description: 'The app verifies the integrity of its resources.',
  ),
  MasweWeakness(
    id: 'MASWE-0058',
    title: 'Runtime Code Integrity Not Verified',
    category: 'MASVS-RESILIENCE',
    platforms: ['android', 'ios'],
    cweIds: [],
    description:
        'The app detects unauthorized changes to its code and execution flow at runtime.',
  ),
  MasweWeakness(
    id: 'MASWE-0059',
    title: 'Code Obfuscation Not Implemented',
    category: 'MASVS-RESILIENCE',
    platforms: ['android', 'ios'],
    cweIds: [693],
    description: 'The app implements code obfuscation.',
  ),
  MasweWeakness(
    id: 'MASWE-0060',
    title: 'Resource Obfuscation Not Implemented',
    category: 'MASVS-RESILIENCE',
    platforms: ['android', 'ios'],
    cweIds: [693],
    description:
        'The app applies resource obfuscation to hinder reverse engineering.',
  ),
  MasweWeakness(
    id: 'MASWE-0061',
    title: 'Debug Artifacts Not Removed',
    category: 'MASVS-RESILIENCE',
    platforms: ['android', 'ios'],
    cweIds: [489, 497, 540, 912, 1295],
    description: 'The app does not contain debug artifacts.',
  ),
  MasweWeakness(
    id: 'MASWE-0062',
    title: 'No Application-Level Payload Encryption',
    category: 'MASVS-RESILIENCE',
    platforms: ['android', 'ios'],
    cweIds: [319],
    description:
        'The app applies application-level payload encryption in addition to transport-layer encryption.',
  ),
  MasweWeakness(
    id: 'MASWE-0063',
    title: 'Debug Mechanisms Not Disabled',
    category: 'MASVS-RESILIENCE',
    platforms: ['android', 'ios'],
    cweIds: [489],
    description: 'The app disables debug mechanisms.',
  ),
  MasweWeakness(
    id: 'MASWE-0064',
    title: 'Debugger Detection Not Implemented',
    category: 'MASVS-RESILIENCE',
    platforms: ['android', 'ios'],
    cweIds: [],
    description:
        'The app detects debugger attachment at runtime and responds to protect sensitive operations.',
  ),
  MasweWeakness(
    id: 'MASWE-0065',
    title: 'Dynamic Analysis Tools Detection Not Implemented',
    category: 'MASVS-RESILIENCE',
    platforms: ['android', 'ios'],
    cweIds: [],
    description:
        'The app detects dynamic analysis tools and responds to protect sensitive operations.',
  ),
  MasweWeakness(
    id: 'MASWE-0066',
    title: 'Inadequate Permission Management',
    category: 'MASVS-PRIVACY',
    platforms: ['android', 'ios'],
    cweIds: [250],
    description: 'The app adequately manages permissions.',
  ),
  MasweWeakness(
    id: 'MASWE-0067',
    title: 'Lack of Anonymization or Pseudonymisation Measures',
    category: 'MASVS-PRIVACY',
    platforms: ['android', 'ios'],
    cweIds: [359],
    description: 'The app uses anonymization or pseudonymisation measures.',
  ),
  MasweWeakness(
    id: 'MASWE-0068',
    title: 'Incorrect Use of Identifiers for User Tracking',
    category: 'MASVS-PRIVACY',
    platforms: ['android', 'ios'],
    cweIds: [359],
    description:
        'The app does not use persistent or unique identifiers in a way that enables user tracking.',
  ),
  MasweWeakness(
    id: 'MASWE-0069',
    title: 'Usage of Non-Privacy-Preserving Functionality',
    category: 'MASVS-PRIVACY',
    platforms: ['android', 'ios'],
    cweIds: [359],
    description: 'The app uses privacy-preserving functionality.',
  ),
  MasweWeakness(
    id: 'MASWE-0070',
    title: 'Inadequate Awareness for Privacy Relevant Actions',
    category: 'MASVS-PRIVACY',
    platforms: ['android', 'ios'],
    cweIds: [359],
    description:
        'The app informs the user about the privacy implications before performing an action.',
  ),
  MasweWeakness(
    id: 'MASWE-0071',
    title: 'Inadequate Defaults for Privacy Relevant Actions',
    category: 'MASVS-PRIVACY',
    platforms: ['android', 'ios'],
    cweIds: [359],
    description: 'The app uses adequate defaults for privacy relevant actions.',
  ),
  MasweWeakness(
    id: 'MASWE-0072',
    title: 'Inadequate Privacy Policy',
    category: 'MASVS-PRIVACY',
    platforms: ['android', 'ios'],
    cweIds: [359],
    description: 'The app provides an adequate privacy policy.',
  ),
  MasweWeakness(
    id: 'MASWE-0073',
    title: 'Inadequate Data Collection Declarations',
    category: 'MASVS-PRIVACY',
    platforms: ['android', 'ios'],
    cweIds: [359],
    description: 'The app adequately declares all user collected data.',
  ),
  MasweWeakness(
    id: 'MASWE-0074',
    title: 'Inadequate Tracking Domains Declarations',
    category: 'MASVS-PRIVACY',
    platforms: ['android', 'ios'],
    cweIds: [359],
    description:
        'The app adequately declares all tracking domains it connects to.',
  ),
  MasweWeakness(
    id: 'MASWE-0075',
    title: 'Non-Reproducible Builds',
    category: 'MASVS-PRIVACY',
    platforms: ['android', 'ios'],
    cweIds: [1357, 494],
    description: 'The app offers reproducible builds.',
  ),
  MasweWeakness(
    id: 'MASWE-0076',
    title: 'Lack of Proper Data Management Controls',
    category: 'MASVS-PRIVACY',
    platforms: ['android', 'ios'],
    cweIds: [359],
    description: 'The app provides adequate controls to manage user data.',
  ),
  MasweWeakness(
    id: 'MASWE-0077',
    title: 'Inadequate Data Visibility Controls',
    category: 'MASVS-PRIVACY',
    platforms: ['android', 'ios'],
    cweIds: [359],
    description:
        'The app provides adequate controls over the visibility of user data.',
  ),
  MasweWeakness(
    id: 'MASWE-0078',
    title: 'Inadequate or Ambiguous User Consent Mechanisms',
    category: 'MASVS-PRIVACY',
    platforms: ['android', 'ios'],
    cweIds: [200, 285, 358, 359],
    description: 'The app requests user consent prior to any data processing.',
  ),
];

/// Oude beta-id's (MASWE v0.x, tot 0119) naar de canonieke
/// zwakheid die ze heeft opgeslokt. De gebundelde MASTG v2.0.0
/// verwijst nog naar de beta-nummering; deze brug houdt die
/// kruiskoppeling heel zonder de MASTG-data te vervalsen.
const Map<String, String> _betaAliases = {
  'MASWE-0079': 'MASWE-0050',
  'MASWE-0080': 'MASWE-0050',
  'MASWE-0081': 'MASWE-0050',
  'MASWE-0082': 'MASWE-0050',
  'MASWE-0083': 'MASWE-0050',
  'MASWE-0084': 'MASWE-0050',
  'MASWE-0085': 'MASWE-0049',
  'MASWE-0086': 'MASWE-0050',
  'MASWE-0087': 'MASWE-0050',
  'MASWE-0088': 'MASWE-0050',
  'MASWE-0089': 'MASWE-0059',
  'MASWE-0090': 'MASWE-0060',
  'MASWE-0091': 'MASWE-0059',
  'MASWE-0092': 'MASWE-0059',
  'MASWE-0093': 'MASWE-0061',
  'MASWE-0094': 'MASWE-0061',
  'MASWE-0095': 'MASWE-0061',
  'MASWE-0096': 'MASWE-0062',
  'MASWE-0097': 'MASWE-0051',
  'MASWE-0098': 'MASWE-0052',
  'MASWE-0099': 'MASWE-0053',
  'MASWE-0100': 'MASWE-0054',
  'MASWE-0101': 'MASWE-0064',
  'MASWE-0102': 'MASWE-0065',
  'MASWE-0103': 'MASWE-0053',
  'MASWE-0104': 'MASWE-0056',
  'MASWE-0105': 'MASWE-0057',
  'MASWE-0106': 'MASWE-0056',
  'MASWE-0107': 'MASWE-0058',
  'MASWE-0108': 'MASWE-0073',
  'MASWE-0109': 'MASWE-0067',
  'MASWE-0110': 'MASWE-0068',
  'MASWE-0111': 'MASWE-0072',
  'MASWE-0112': 'MASWE-0073',
  'MASWE-0113': 'MASWE-0076',
  'MASWE-0114': 'MASWE-0077',
  'MASWE-0115': 'MASWE-0078',
  'MASWE-0116': 'MASWE-0045',
  'MASWE-0117': 'MASWE-0066',
  'MASWE-0118': 'MASWE-0001',
  'MASWE-0119': 'MASWE-0018',
};
