// GEGENEREERD door tool/build_maswe_catalog.dart — niet met de
// hand bijwerken. Zie dat bestand voor de bron en de regels.
//
// OWASP MASWE, © de OWASP Foundation, CC-BY-SA-4.0.
part of 'maswe_catalog.dart';

/// De MASWE-zwakheden die uitgeschreven zijn (28).
const List<MasweWeakness> _writtenWeaknesses = [
  MasweWeakness(
    id: 'MASWE-0001',
    title: 'Insertion of Sensitive Data into Logs',
    category: 'MASVS-STORAGE',
    platforms: ['android', 'ios'],
    cweIds: [209, 359, 497, 532],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0004',
    title: 'Sensitive Data Not Excluded From Backup',
    category: 'MASVS-STORAGE',
    platforms: ['android', 'ios'],
    cweIds: [212],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0005',
    title: 'API Keys Hardcoded in the App Package',
    category: 'MASVS-AUTH',
    platforms: ['android', 'ios'],
    cweIds: [798],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0006',
    title: 'Sensitive Data Stored Unencrypted in Private Storage Locations',
    category: 'MASVS-STORAGE',
    platforms: ['android', 'ios'],
    cweIds: [312, 313, 922],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0007',
    title:
        'Sensitive Data Stored Unencrypted in Shared Storage Requiring No User Interaction',
    category: 'MASVS-STORAGE',
    platforms: ['android'],
    cweIds: [312, 313, 921, 922],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0009',
    title: 'Improper Cryptographic Key Generation',
    category: 'MASVS-CRYPTO',
    platforms: ['android', 'ios'],
    cweIds: [331, 337, 338],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0014',
    title: 'Cryptographic Keys Not Properly Protected at Rest',
    category: 'MASVS-CRYPTO',
    platforms: ['android', 'ios'],
    cweIds: [312, 318, 321],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0019',
    title: 'Risky Cryptography Implementations',
    category: 'MASVS-CRYPTO',
    platforms: ['android', 'ios'],
    cweIds: [326, 327, 1240],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0020',
    title: 'Improper Encryption',
    category: 'MASVS-CRYPTO',
    platforms: ['android', 'ios'],
    cweIds: [326],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0023',
    title: 'Risky Padding',
    category: 'MASVS-CRYPTO',
    platforms: ['android', 'ios'],
    cweIds: [208, 325, 327, 780],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0027',
    title: 'Improper Random Number Generation',
    category: 'MASVS-CRYPTO',
    platforms: ['android', 'ios'],
    cweIds: [332, 337, 338],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0047',
    title: 'Insecure Identity Pinning',
    category: 'MASVS-NETWORK',
    platforms: ['android', 'ios'],
    cweIds: [295],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0049',
    title: 'Proven Networking APIs Not used',
    category: 'MASVS-NETWORK',
    platforms: ['android', 'ios'],
    cweIds: [],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0050',
    title: 'Cleartext Traffic',
    category: 'MASVS-NETWORK',
    platforms: ['android', 'ios'],
    cweIds: [319],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0051',
    title: 'Unprotected Open Ports',
    category: 'MASVS-NETWORK',
    platforms: ['android', 'ios'],
    cweIds: [923],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0052',
    title: 'Insecure Certificate Validation',
    category: 'MASVS-NETWORK',
    platforms: ['android', 'ios'],
    cweIds: [295, 297],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0055',
    title: 'Sensitive Data Leaked via Screenshots or Screen Recordings',
    category: 'MASVS-PLATFORM',
    platforms: ['android', 'ios'],
    cweIds: [200, 359],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0067',
    title: 'Debuggable Flag Not Disabled',
    category: 'MASVS-RESILIENCE',
    platforms: ['android', 'ios'],
    cweIds: [489],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0076',
    title: 'Dependencies with Known Vulnerabilities',
    category: 'MASVS-CODE',
    platforms: ['android', 'ios'],
    cweIds: [1395, 1357],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0108',
    title: 'Sensitive Data in Network Traffic',
    category: 'MASVS-PRIVACY',
    platforms: ['android', 'ios'],
    cweIds: [359],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0109',
    title: 'Lack of Anonymization or Pseudonymisation Measures',
    category: 'MASVS-PRIVACY',
    platforms: ['android', 'ios'],
    cweIds: [359],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0110',
    title: 'Use of Unique Identifiers for User Tracking',
    category: 'MASVS-PRIVACY',
    platforms: ['android', 'ios'],
    cweIds: [359],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0111',
    title: 'Inadequate Privacy Policy',
    category: 'MASVS-PRIVACY',
    platforms: ['android', 'ios'],
    cweIds: [359],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0112',
    title: 'Inadequate Data Collection Declarations',
    category: 'MASVS-PRIVACY',
    platforms: ['android', 'ios'],
    cweIds: [359],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0113',
    title: 'Lack of Proper Data Management Controls',
    category: 'MASVS-PRIVACY',
    platforms: ['android', 'ios'],
    cweIds: [359],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0114',
    title: 'Inadequate Data Visibility Controls',
    category: 'MASVS-PRIVACY',
    platforms: ['android', 'ios'],
    cweIds: [359],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0115',
    title: 'Inadequate or Ambiguous User Consent Mechanisms',
    category: 'MASVS-PRIVACY',
    platforms: ['android', 'ios'],
    cweIds: [359],
    isPlaceholder: false,
  ),
  MasweWeakness(
    id: 'MASWE-0117',
    title: 'Inadequate Permission Management',
    category: 'MASVS-PRIVACY',
    platforms: ['android', 'ios'],
    cweIds: [250],
    isPlaceholder: false,
  ),
];
