// Builds assets/improvement/templates.json (+ generated floor) from the
// Markdown template sources in assets/improvement/templates/*.md.
//
//   dart run tool/build_improvement_templates.dart
//
// Source of truth is the Markdown files (PROCESS_IMPROVEMENT.md §2 / §8). Adding
// Kano later = drop in a .md and re-run this tool — no hand-edited Dart catalog.
import 'dart:convert';
import 'dart:io';

import 'package:yaml/yaml.dart';

const _srcDir = 'assets/improvement/templates';
const _jsonOut = 'assets/improvement/templates.json';
const _floorOut = 'lib/services/improvement/improvement_templates_floor.g.dart';

void main(List<String> args) {
  final dir = Directory(_srcDir);
  if (!dir.existsSync()) {
    stderr.writeln('missing $_srcDir');
    exit(1);
  }
  final files =
      dir
          .listSync()
          .whereType<File>()
          .where((f) => f.path.endsWith('.md'))
          .toList()
        ..sort((a, b) => a.path.compareTo(b.path));
  if (files.isEmpty) {
    stderr.writeln('no .md templates in $_srcDir');
    exit(1);
  }

  final templates = <Map<String, Object?>>[];
  for (final file in files) {
    templates.add(_parseTemplateFile(file));
  }
  templates.sort((a, b) => (a['id'] as String).compareTo(b['id'] as String));

  final envelope = <String, Object?>{
    '_comment':
        'GENERATED by tool/build_improvement_templates.dart — do not edit by '
        'hand. Source: assets/improvement/templates/*.md',
    'source': 'ocideck',
    'version': '1',
    'templates': templates,
  };

  final jsonText = const JsonEncoder.withIndent('  ').convert(envelope);
  File(_jsonOut).writeAsStringSync('$jsonText\n');
  stdout.writeln('Wrote ${templates.length} templates to $_jsonOut');

  final floor = StringBuffer()
    ..writeln(
      '// GENERATED by tool/build_improvement_templates.dart — do not edit.',
    )
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln(
      '/// Offline floor for [ImprovementTemplateCatalog], identical to',
    )
    ..writeln('/// `assets/improvement/templates.json` at the last build.')
    ..writeln(
      'const String kImprovementTemplatesFloorJson = ${jsonEncode(jsonText)};',
    );
  File(_floorOut).writeAsStringSync(floor.toString());
  stdout.writeln('Wrote floor to $_floorOut');
}

Map<String, Object?> _parseTemplateFile(File file) {
  final raw = file.readAsStringSync();
  if (!raw.startsWith('---\n')) {
    stderr.writeln('${file.path}: missing opening front matter');
    exit(1);
  }
  final end = raw.indexOf('\n---\n', 4);
  if (end < 0) {
    stderr.writeln('${file.path}: missing closing front matter');
    exit(1);
  }
  final yamlText = raw.substring(4, end);
  final body = raw.substring(end + 5).trimRight();
  final yaml = loadYaml(yamlText);
  if (yaml is! YamlMap) {
    stderr.writeln('${file.path}: front matter is not a map');
    exit(1);
  }
  final map = _yamlToJson(yaml) as Map<String, Object?>;
  final id = map['id'];
  final engine = map['engine'];
  if (id is! String || id.isEmpty || engine is! String || engine.isEmpty) {
    stderr.writeln('${file.path}: id and engine are required');
    exit(1);
  }
  if (body.isNotEmpty) {
    map['body'] = body;
  }
  return map;
}

Object? _yamlToJson(Object? node) {
  if (node is YamlMap) {
    return {
      for (final e in node.entries) e.key.toString(): _yamlToJson(e.value),
    };
  }
  if (node is YamlList) {
    return [for (final e in node) _yamlToJson(e)];
  }
  return node;
}
