// Guards that a machine-translated document does not carry an English mermaid
// diagram (#1278).
//
// The translated `.<lang>.md` variants are generated by `tool/translate_docs.dart`:
// the whole Markdown body is handed to an external translator, which — like every
// sane translator — leaves fenced code blocks untouched so it cannot break their
// syntax. A ```mermaid block is technically a code block, so its *label text*
// ("New or open a deck" …) stays in the source language while the prose around it
// gets translated. A Dutch reader then sees an English diagram in the middle of a
// Dutch guide (#1278: "plaatjes in Nederlandse handleiding zijn engels").
//
// This gate catches that whole class, for every current and future language: for
// each generated variant it compares each ```mermaid block byte-for-byte against
// the same block in the English base. A variant block that is byte-identical to
// the base block is an untranslated diagram — unless it is genuinely
// language-neutral (only node IDs, numbers, arrows), in which case it is listed in
// [languageNeutralMermaidBlocks]. That whitelist is deliberately explicit: a
// diagram carrying no prose is identical in every language *by nature*, and keying
// the exemption on the block body means one entry covers every language at once.
//
// The gate does not translate anything — it only refuses the English-in-place
// state. Fixing a hit means translating the diagram's labels by hand (the node IDs
// and mermaid syntax stay), because we do not machine-translate mermaid: see the
// note in `tool/translate_docs.dart`.
//
// Deliberately dependency-free: this runs in `STATIC_GATES` via `dart run`, so it
// imports only `dart:io` — never `package:ocideck`. A tool that pulls in the app
// package drags the native FFI layer through the `dart run` kernel compiler, which
// crashes on this toolchain; a static gate must not hinge on the app compiling.
// It therefore discovers variants from the `docs/` filenames rather than from
// `translate_docs.dart`'s document/language lists.

import 'dart:io';

/// Normalised bodies of ```mermaid blocks that are allowed to be byte-identical
/// between a translated variant and the English base, because they carry no
/// human-readable prose to translate (only node IDs, numbers and arrows).
///
/// Deliberately empty today: every bundled diagram has prose labels. Add a body
/// here — trimmed exactly as [normaliseBlock] returns it — only when a diagram is
/// genuinely language-neutral, with a comment saying why.
const Set<String> languageNeutralMermaidBlocks = {};

/// A base English document paired with one of its translated variants, both as
/// full Markdown. The comparison unit for [findUntranslatedMermaid].
class TranslatedDoc {
  const TranslatedDoc({
    required this.basePath,
    required this.baseMarkdown,
    required this.variantPath,
    required this.variantMarkdown,
  });

  final String basePath;
  final String baseMarkdown;
  final String variantPath;
  final String variantMarkdown;
}

/// One untranslated diagram: the same ```mermaid block in a translated variant as
/// in its English base source.
class MermaidCollision {
  const MermaidCollision({
    required this.variantPath,
    required this.basePath,
    required this.blockIndex,
    required this.body,
  });

  final String variantPath;
  final String basePath;

  /// Zero-based index of the mermaid block within the document, so a doc with
  /// several diagrams still points at the offending one.
  final int blockIndex;

  /// The shared (byte-identical) block body, for the failure message.
  final String body;
}

/// The bodies of every ```mermaid fenced block in [markdown], in document order.
/// The body is the text between the opening ` ```mermaid ` fence line and its
/// closing ` ``` ` line, verbatim (no trimming) so the comparison is byte-exact.
List<String> mermaidBlocks(String markdown) {
  final blocks = <String>[];
  final lines = markdown.split('\n');
  var inBlock = false;
  var current = <String>[];
  for (final line in lines) {
    final trimmed = line.trimRight();
    if (!inBlock) {
      // Opening fence: ```mermaid, optionally with trailing info after the word.
      if (RegExp(r'^```mermaid\b').hasMatch(trimmed)) {
        inBlock = true;
        current = <String>[];
      }
      continue;
    }
    if (trimmed == '```') {
      blocks.add(current.join('\n'));
      inBlock = false;
      continue;
    }
    current.add(line);
  }
  return blocks;
}

/// Trims a block body for whitelist comparison, so trailing-whitespace noise does
/// not force a re-listing. The collision check itself stays byte-exact; only the
/// exemption lookup is normalised.
String normaliseBlock(String body) => body.trim();

/// Pairs a translated variant filename with its English base. Pure so it can be
/// unit-tested: given the `.md` filenames present in a directory, it returns the
/// (base, variant) pairs where a `NAME.<lang>.md` has a matching `NAME.md`. A
/// language segment is a short lowercase code, optionally with a script/region
/// suffix (`nl`, `pt`, `zh-Hant`); a base name such as `FILE_FORMAT` has no such
/// segment and so is never mistaken for a variant.
List<({String base, String variant})> pairVariantsWithBase(
  Iterable<String> mdFileNames,
) {
  final present = mdFileNames.toSet();
  final langSegment = RegExp(r'^[a-z]{2,3}(-[A-Za-z]{2,4})?$');
  final pairs = <({String base, String variant})>[];
  for (final name in mdFileNames) {
    if (!name.endsWith('.md')) continue;
    final stem = name.substring(0, name.length - '.md'.length);
    final dot = stem.lastIndexOf('.');
    if (dot < 0) continue; // no infix → a base document, not a variant
    final seg = stem.substring(dot + 1);
    if (!langSegment.hasMatch(seg)) continue;
    final base = '${stem.substring(0, dot)}.md';
    if (present.contains(base)) pairs.add((base: base, variant: name));
  }
  return pairs;
}

/// Every translated mermaid block that is byte-identical to its English base
/// block and not exempted. Pure and content-injected so the test can drive it
/// without touching disk.
List<MermaidCollision> findUntranslatedMermaid(
  Iterable<TranslatedDoc> docs, {
  Set<String> whitelist = languageNeutralMermaidBlocks,
}) {
  final collisions = <MermaidCollision>[];
  for (final doc in docs) {
    final baseBlocks = mermaidBlocks(doc.baseMarkdown);
    if (baseBlocks.isEmpty) continue;
    final variantBlocks = mermaidBlocks(doc.variantMarkdown);
    final shared = baseBlocks.length < variantBlocks.length
        ? baseBlocks.length
        : variantBlocks.length;
    for (var i = 0; i < shared; i++) {
      if (baseBlocks[i] != variantBlocks[i]) continue;
      if (whitelist.contains(normaliseBlock(baseBlocks[i]))) continue;
      collisions.add(
        MermaidCollision(
          variantPath: doc.variantPath,
          basePath: doc.basePath,
          blockIndex: i,
          body: baseBlocks[i],
        ),
      );
    }
  }
  return collisions;
}

/// Reads `docs/` and builds the base/variant pairs from what is on disk.
List<TranslatedDoc> _loadTranslatedDocs(String docsDir) {
  final dir = Directory(docsDir);
  if (!dir.existsSync()) return const [];
  final names = dir
      .listSync()
      .whereType<File>()
      .map((f) => f.uri.pathSegments.last)
      .toList();
  return [
    for (final pair in pairVariantsWithBase(names))
      TranslatedDoc(
        basePath: '$docsDir/${pair.base}',
        baseMarkdown: File('$docsDir/${pair.base}').readAsStringSync(),
        variantPath: '$docsDir/${pair.variant}',
        variantMarkdown: File('$docsDir/${pair.variant}').readAsStringSync(),
      ),
  ];
}

void main() {
  final collisions = findUntranslatedMermaid(_loadTranslatedDocs('docs'));

  if (collisions.isEmpty) {
    stdout.writeln(
      'check-translated-mermaid: OK (no English mermaid diagram in a '
      'translated document).',
    );
    return;
  }

  stderr.writeln(
    'check-translated-mermaid: ${collisions.length} untranslated mermaid '
    'diagram(s) — a translated document carries an English diagram (#1278).',
  );
  for (final c in collisions) {
    stderr.writeln(
      '  ${c.variantPath}: mermaid block #${c.blockIndex + 1} is '
      'byte-identical to ${c.basePath}',
    );
  }
  stderr
    ..writeln('')
    ..writeln(
      'The translator leaves code blocks (and so mermaid) untouched, so a '
      'diagram\'s labels must be translated by hand:',
    )
    ..writeln('  - translate the label text inside [ ], keeping node IDs and')
    ..writeln('    mermaid syntax intact;')
    ..writeln(
      '  - or, if the diagram is genuinely language-neutral, add its body to',
    )
    ..writeln(
      '    languageNeutralMermaidBlocks in tool/check_translated_mermaid.dart.',
    );
  exit(1);
}
